name: DataSchemaCodeConversion  # Назва роботи

on:
  push:
    branches:
      - LW11  # Запуск роботи лише при push до гілки з назвою LW11

jobs:
  data_schema_code_conversion:  # Назва задачі
    runs-on: ubuntu-latest  # Використання ОС ubuntu-latest для виконання роботи

    steps:
      - name: Checkout Code in Repository  # Крок для вибору коду з репозиторію
        uses: actions/checkout@v3  # Використання дії для вибору коду

      - name: Start DataSchemaCodeConversion  # Назва кроку
        run: |  # Багатостроковий блок команд
          pip install sqlfluff  # Встановлення sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/DataSchema.sql --dialect postgres  # Виконання перевірки SQL файлу
