# https://github.com/marketplace/actions/super-linter
name: Program Code Linter
on:
  push:
     branches:
      - LW11
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Compile Java code
      run: javac ProgramCode.java
