name: Java Test Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Find TestCases.java
      run: find ./ -name "TestCases.java"

    - name: Compile and Run JUnit tests
      run: |
        javac -cp junit-platform-console-standalone-1.8.2.jar:. $(find ./ -name "TestCases.java")
        java -jar junit-platform-console-standalone-1.8.2.jar --class-path . --scan-class-path
