name: Java Test Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SOURCE_FILE_PATH: src/main/TestCases.java

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - run: javac -cp junit-platform-console-standalone-1.8.2.jar:. ${{ env.SOURCE_FILE_PATH }}

    - run: java -jar junit-platform-console-standalone-1.8.2.jar --class-path . --scan-class-path
